name: friends_secrets
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Modular
  flutter_modular: ^4.2.0
  asuka: ^2.0.0
  # State Manager
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  # Firebase
  firebase_analytics: ^9.1.0
  firebase_core: ^1.6.0
  firebase_messaging: ^11.2.2
  firebase_auth: ^3.3.7
  # Google
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  # HTTP
  dio: ^4.0.0
  # Generate
  dartz: ^0.10.0
  equatable: ^2.0.3
  # Storage
  shared_preferences: ^2.0.8
  # Image
  image_picker: ^0.8.4+4
  flutter_svg: ^1.0.2
  # Android
  flutter_contacts: ^1.1.2
  permission_handler: ^8.3.0
  uni_links: ^0.5.1
  mask_text_input_formatter: ^2.1.0
  badges: ^2.0.2
  edge_alert: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  modular_codegen: ^3.0.2
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.1
  mockito: ^5.0.15
  faker: ^2.0.0
  modular_test: ^1.0.1+1
  flutter_dotenv: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
