name: Build Develop

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Validation Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.x"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash

  build:
    name: Build IOS
    needs: [quality]
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "build/app/outputs/bundle/release/*.aab"

  build:
    name: Build Android
    needs: [quality]
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Build Android App
        run: |
          flutter build apk --split-per-abi
          flutter build appbundle

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"