name: Build Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  flutter_version: "2.10.1"
  flutter_channel: "stable"

jobs:
  test:
    name: Validation Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.x"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash

  build:
    name: Build Apps
    needs: [test]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)'
          tagRegexGroup: 1

      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
          echo "Tag used version:"$GIT_TAG_NAME

      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: macos-flutter

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install pub Dependencies
        run: flutter pub get

      # - name: Build iOS App
      #   run: |
      #     flutter build ios --release --dart-define=ENV=PROD --no-codesign

      - name: Build Android App
        run: |
          flutter build appbundle --release --dart-define=ENV=PROD
          flutter build apk --release --dart-define=ENV=PROD
        env:
          IS_SIGNING_ENABLED: false

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.GIT_TAG_NAME }}
          name: ${{ env.GIT_TAG_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
