name: Build Develop

on:
  push:
    branches: [develop]

jobs:
  test:
    name: Validation Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.x"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Test validation
        run: flutter test

  quality:
    name: Quality dart Code
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.x"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install dependencies
        run: dart pub get

      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1

  build:
    name: Build Apps ${{ matrix.project}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [quality]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Build Android App
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          flutter build apk --split-per-abi
          flutter build appbundle

      - name: Build iOS App
        if: startsWith(matrix.os, 'macOS')
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # - name: Build Web App
      #   run: |
      #     flutter build web
      #     cd build/web
      #     zip -r web-app.zip .

      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab,build/ios/iphoneos/*.ipa"
