# Run iOS build when there are changes in `ios/` folder in a PR pointing to `master`.
name: iOS Build

on:
  pull_request:
    branches:
      - master
    paths:
      - "ios/**"

env:
  flutter_version: "2.8.1"
  flutter_channel: "stable"

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2 # that generate $GIT_TAG_NAME env
        id: tagName
        with:
          tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
          echo "Tag used version:"$GIT_TAG_NAME

      # Caches Flutter repository so it can be reused by future workflows run
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: macos-flutter

      # Setup Flutter SDK with version `env.flutter_version`
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}

      # Build iOS app in production environment without code sign
      - name: Build iOS App
        run: flutter build ios --release --dart-define=ENV=PROD --no-codesign
