name: pipeline

on:
  push:
    branches: [develop, master, releases/**]

jobs:
  preparing_environment:
    runs-on: ubuntu-latest
    name: Preparação do Ambiente

  build_ios:
    runs-on: macos-latest
    needs: [preparing_environment]
    name: Build iOS

  build_android:
    runs-on: ubuntu-latest
    needs: [preparing_environment]
    name: Build Android

  quality:
    runs-on: ubuntu-latest
    needs: [build_ios, build_android]
    name: Qualidade

  checkstyle:
    runs-on: ubuntu-latest
    needs: [build_ios, build_android]
    name: Check Style

  lint:
    runs-on: ubuntu-latest
    needs: [checkstyle]
    name: Lint

  detekt:
    runs-on: ubuntu-latest
    needs: [checkstyle]
    name: Detekt

  unit_test:
    runs-on: ubuntu-latest
    needs: [build_ios, build_android]
    name: Unit Test

  coverage:
    runs-on: ubuntu-latest
    needs: [unit_test]
    name: Cobertura

  preparing_delivery:
    runs-on: ubuntu-latest
    needs: [quality, detekt, coverage]
    name: Preparando Delivery

  alpha:
    runs-on: ubuntu-latest
    if: github.repository == 'develop'
    needs: [preparing_delivery]
    name: Preparando Delivery

  beta:
    if: github.repository == 'releases/**'
    runs-on: ubuntu-latest
    needs: [preparing_delivery]
    name: Preparando Delivery

  play Store:
    if: github.repository == 'master'
    runs-on: ubuntu-latest
    needs: [preparing_delivery]
    name: Preparando Delivery
