name: Release

on:
  release:
    types:
      - published

env:
  flutter_version: "2.5.3"
  java_version: "12.x"
  flutter_channel: "stable"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Checkout to master branch because this workflow is triggered from a release publish, it means that
          # actions/checkout checkouts to HEAD by default. We need to be in master branch to commit and push the bumped
          # version files changes - this workflow last phase
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      # Setup Java SDK with version `env.java_version`, required by Flutter to build the Android app
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      # Caches Flutter repository so it can be reused by future workflows run
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: macos-flutter

      # Setup Flutter SDK with version `env.flutter_version`
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}

     - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab,build/ios/iphoneos/*.ipa"